[package]
name = "binverse_derive"
authors = ["Linus Dikomey"]
license = "MIT"
readme = "../README.md"
version = "0.3.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "fold"] }
quote = "1.0"